[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Sky Brewer <jacobrewer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path ="src/main.rs"
name ="zero2prod"

[dependencies]
actix-web = "4.0.0-beta.3"
serde = "1.0.118"
config = { version = "0.10.1", default-features = false, features = ["yaml"] }
sqlx = { version = "0.5.1", default-features = false, features = ["runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"] }
uuid = { version = "0.8.1", features = ["v4"] }
chrono = "0.4.19"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
tracing = "0.1.22"
tracing-futures = "0.2.4"
tracing-subscriber ={ version = "0.2.15", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.1.7"
tracing-log = "0.1.1"
tracing-actix-web = "0.3.0-beta"
serde-aux = "1.1.0"
unicode-segmentation = "1.7.1"
validator = "0.12.0"

[dev-dependencies]
claim = "0.4.0"
lazy_static = "1.4.0"
tokio = {version = "1", features=["macros"]}
fake = "~2.3"
serde_json = "1"
quickcheck = "0.9"
quickcheck_macros = "0.9"
wiremock = "0.4.9"
actix-rt = "2"