[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Sky Brewer <jacobrewer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path ="src/main.rs"
name ="app"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
config = "0.10.1"
serde = {version = "1.0.118", features = ["derive"]}
sqlx = { version = "0.4.1", features = ["postgres","runtime-actix-rustls","macros","uuid","chrono","migrate"], default-features = false }

[dev-dependencies]
reqwest = ""
tokio =""
