# fly.toml file generated for zero2prod on 2022-03-29T15:28:49+02:00

app = "zero2prod"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = "./zero2prod"

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "8000"
    restart_limit = 0
    timeout = "2s"
